SELECT * FROM play_store;
-- Total Number of Apps by Category:
-- Count the number of apps in each category.
SELECT Category,COUNT(App)
FROM play_store
GROUP BY Category;

-- Top 5 Apps with the Highest Ratings:
-- Identify the top 5 apps with the highest user ratings.
SELECT App,Rating
FROM play_store
ORDER BY Rating DESC
LIMIT 5;

-- Average Size of Apps by Category:
-- Calculate the average size of apps in each category.
SELECT Category,AVG(Size)
FROM play_store
GROUP BY Category;

-- Percentage of Free vs. Paid Apps:
-- Determine the percentage of free and paid apps in the dataset.
SELECT App,(COUNT(CASE WHEN Type="Free" THEN 1 END)/COUNT(*)*100) as FreePercentage
FROM play_store
GROUP BY App;

SELECT App,(COUNT(CASE WHEN Type="Paid" THEN 1 END)/COUNT(*)*100) as PaidPercentage
FROM play_store
GROUP BY App;

-- Top 5 Apps with the Highest Number of Reviews:
-- Identify the top 5 apps with the highest number of reviews.
SELECT App,Reviews
FROM play_store
ORDER BY Reviews DESC
LIMIT 5;

-- Top 3 Genres with the Most Installs:
-- Determine the top 3 genres with the highest total number of installs.
SELECT Genres,SUM(CAST(REPLACE(Installs,',','') AS SIGNED)) as TotalInstalls
FROM play_store
GROUP BY Genres
ORDER BY TotalInstalls DESC
LIMIT 3;

-- Correlation between Size and Rating:
-- Calculate the correlation coefficient between the size of an app and its user rating.
SELECT (COUNT(*) * SUM(Size * Rating) - SUM(Size) * SUM(Rating)) / 
(SQRT((COUNT(*) * SUM(Size * Size) - SUM(Size) * SUM(Size)) * (COUNT(*) * SUM(Rating * Rating) - SUM(Rating) * SUM(Rating))))
AS correlation
FROM play_store
WHERE Size IS NOT NULL AND Rating IS NOT NULL;

-- Calculate the correlation coefficient between the Installs and its user rating.
SELECT (COUNT(*) * SUM(Installs * Rating) - SUM(Installs) * SUM(Rating))/
(SQRT((COUNT(*) * SUM(Installs * Installs) - SUM(Installs) * SUM(Installs)) * (COUNT(*) * SUM(Rating * Rating) - SUM(Rating) * SUM(Rating))))
As correlation
FROM play_store
WHERE Installs IS NOT NULL AND Rating IS NOT NULL;

-- Number of Apps per Content Rating:
-- Count the number of apps for each content rating (Everyone, Teen, Mature, etc.).
SELECT ContentRating,COUNT(App)
FROM play_store
GROUP BY ContentRating;

-- Average Price of Apps by Category:
-- Find the average price of apps in each category
SELECT Category,AVG(Price)
FROM play_store
GROUP BY Category;

-- Top 5 Apps with the Highest Revenue (Price x Installs):
-- Calculate the revenue generated by each app (price multiplied by the number of installs) and identify the top 5.
SELECT App,(Price * Installs) as revenue
FROM play_store
ORDER BY revenue DESC
LIMIT 5;
